// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnMyOwn.Models;

namespace OnMyOwn.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20220930170523_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnMyOwn.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("Cost")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Cost = 14.890000000000001,
                            Genre = "Non-Fiction",
                            Title = "Banana: The Fate of the Fruit That Changed the World",
                            Year = 2008
                        },
                        new
                        {
                            BookId = 2,
                            Cost = 18.0,
                            Genre = "Non-Fiction",
                            Title = "Bananeras: Women Transforming the Banana Unions of Latin America",
                            Year = 2005
                        },
                        new
                        {
                            BookId = 3,
                            Cost = 11.99,
                            Genre = "Non-Fiction",
                            Title = "Banana Cultures: Agriculture, Consumption, and Environmental Change in Honuras and the United States",
                            Year = 2006
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
